name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ocaml-compiler:
          - 5
        include:
          - os: ubuntu-latest
            ocaml-compiler: 4.11

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install opam dependencies
        run: |
          # Work around https://github.com/ocaml/setup-ocaml/issues/899
          opam install conf-pkg-config
          opam install . --deps-only --with-test --with-dev-setup

      - env:
          PKG_CONFIG_PATH: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/pkgconfig
        run: opam exec -- dune build

      - run: opam exec -- dune runtest
        if: ${{ runner.os != 'Windows' }}
        # Pinning OpenSSL to 1.1.1w-0.1 doesn't work with new packages
        # expecting OpenSSL 3
        # https://github.com/ocaml/setup-ocaml/issues/947
